import typer
from rich.console import Console
from rich.markdown import Markdown
from review_roadmap.github.client import GitHubClient, find_working_token
from review_roadmap.agent.graph import build_graph
from review_roadmap.config import settings
from review_roadmap.logging import configure_logging
from review_roadmap.models import WriteAccessStatus

app = typer.Typer(add_completion=False)
console = Console()

# Header prefix used to identify roadmap comments for collapse feature
ROADMAP_HEADER_PREFIX = "🗺️ **Auto-Generated Review Roadmap**"

# Initialize structured logging
configure_logging(
    log_level=settings.REVIEW_ROADMAP_LOG_LEVEL,
    log_format=settings.REVIEW_ROADMAP_LOG_FORMAT,
)


def format_pr_comment(roadmap_content: str) -> str:
    """Format the roadmap content as a PR comment with attribution header."""
    provider = settings.REVIEW_ROADMAP_LLM_PROVIDER
    model = settings.REVIEW_ROADMAP_MODEL_NAME
    
    header = f"""{ROADMAP_HEADER_PREFIX}

> This roadmap was automatically generated by [review-roadmap](https://github.com/ambient-code/review-roadmap).
> Model: `{provider}/{model}`

---

"""
    return header + roadmap_content


@app.command()
def generate(
    pr_url: str = typer.Argument(..., help="GitHub PR URL (e.g., owner/repo/123) or 'owner/repo/123' string"),
    output: str = typer.Option(None, "--output", "-o", help="Output file for the roadmap"),
    post: bool = typer.Option(False, "--post", "-p", help="Post the roadmap as a comment on the PR"),
    no_reflection: bool = typer.Option(False, "--no-reflection", help="Skip the self-reflection step")
):
    """Generates a review roadmap for a given Pull Request."""
    
    # Parse PR identifier
    try:
        if "github.com" in pr_url:
            parts = pr_url.rstrip("/").split("/")
            pr_number = int(parts[-1])
            repo = parts[-3]
            owner = parts[-4]
        else:
            owner, repo, pr_number = pr_url.split("/")
            pr_number = int(pr_number)
    except Exception:
        console.print("[red]Invalid PR format. Use 'owner/repo/number' or a full URL.[/red]")
        raise typer.Exit(code=1)

    # Initialize GitHub client (default token for read operations)
    gh_client = GitHubClient()
    
    # Token with write access (may differ from default if using multi-token)
    write_token = None

    # Check write access early if posting is requested (fail fast before LLM generation)
    if post:
        tokens = settings.get_github_tokens()
        
        if len(tokens) > 1:
            console.print(f"[bold blue]Searching {len(tokens)} tokens for write access to {owner}/{repo}...[/bold blue]")
        else:
            console.print(f"[bold blue]Checking write access for {owner}/{repo}...[/bold blue]")
        
        try:
            # Search through available tokens for one with write access
            search_result = find_working_token(owner, repo, pr_number)
            
            if search_result.token:
                write_token = search_result.token
                if search_result.tokens_tried > 1:
                    console.print(f"[green]Write access confirmed (token {search_result.tokens_tried} of {len(tokens)}).[/green]")
                else:
                    console.print("[green]Write access confirmed.[/green]")
                # Update client to use the working token for subsequent operations
                gh_client = GitHubClient(token=write_token)
            elif search_result.access_result.status == WriteAccessStatus.UNCERTAIN:
                console.print(f"[yellow]Warning: {search_result.access_result.message}[/yellow]")
                console.print("[yellow]Proceeding, but posting may fail...[/yellow]")
            else:
                if search_result.tokens_tried > 1:
                    console.print(
                        f"[red]Error: None of the {search_result.tokens_tried} configured tokens have write access.[/red]\n"
                        f"[red]Last error: {search_result.access_result.message}[/red]\n"
                        "[yellow]To use --post, at least one token needs 'Pull requests: Read and write' permission.[/yellow]"
                    )
                else:
                    console.print(
                        f"[red]Error: {search_result.access_result.message}[/red]\n"
                        "[yellow]To use --post, your token needs 'Pull requests: Read and write' permission.[/yellow]"
                    )
                raise typer.Exit(code=1)
        except typer.Exit:
            raise
        except Exception as e:
            console.print(f"[red]Error checking repository access: {e}[/red]")
            raise typer.Exit(code=1)

    console.print(f"[bold blue]Fetching PR {owner}/{repo}#{pr_number}...[/bold blue]")
    
    # 1. Fetch Context
    try:
        pr_context = gh_client.get_pr_context(owner, repo, pr_number)
    except Exception as e:
        console.print(f"[red]Error fetching PR data: {e}[/red]")
        raise typer.Exit(code=1)

    console.print(f"[green]Found PR: {pr_context.metadata.title} (Changed files: {len(pr_context.files)})[/green]")

    # 2. Run LangGraph
    if no_reflection:
        console.print("[bold purple]Generating Roadmap (reflection disabled)...[/bold purple]")
    else:
        console.print("[bold purple]Generating Roadmap with self-reflection (this may take a minute)...[/bold purple]")
    
    graph = build_graph()
    initial_state = {"pr_context": pr_context, "skip_reflection": no_reflection}
    
    result = graph.invoke(initial_state)
    roadmap_content = result.get("roadmap", "")

    # 3. Output - content is generated once and can go to file, PR comment, or both
    if output:
        with open(output, "w", encoding="utf-8") as f:
            f.write(roadmap_content)
        console.print(f"[bold green]Roadmap saved to {output}[/bold green]")

    if post:
        console.print("[bold blue]Posting roadmap to PR...[/bold blue]")
        
        # First, minimize any old roadmap comments (non-fatal if this fails)
        try:
            minimized, errors = gh_client.minimize_old_roadmap_comments(
                owner, repo, pr_number, ROADMAP_HEADER_PREFIX
            )
            if minimized > 0:
                console.print(f"[dim]Collapsed {minimized} previous roadmap(s)[/dim]")
            if errors > 0:
                console.print(f"[yellow]Warning: Failed to collapse {errors} comment(s)[/yellow]")
        except Exception as e:
            console.print(f"[yellow]Warning: Could not collapse old comments: {e}[/yellow]")
        
        # Then post the new comment
        try:
            comment_body = format_pr_comment(roadmap_content)
            gh_client.post_pr_comment(owner, repo, pr_number, comment_body)
            console.print(f"[bold green]Roadmap posted to PR #{pr_number}[/bold green]")
        except Exception as e:
            console.print(f"[red]Error posting comment to PR: {e}[/red]")
            if "403" in str(e):
                console.print(
                    "\n[yellow]This usually means your token lacks write access to this repository.[/yellow]\n"
                    "[yellow]If using a fine-grained PAT, ensure it is configured for this specific repository[/yellow]\n"
                    f"[yellow]with 'Pull requests: Read and write' permission for {owner}/{repo}.[/yellow]"
                )
            raise typer.Exit(code=1)

    # If neither output nor post, print to console
    if not output and not post:
        console.print("\n[bold]--- Generated Roadmap ---[/bold]\n")
        console.print(Markdown(roadmap_content))

if __name__ == "__main__":
    app()
